In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [27]:
iris=pd.read_csv('F:\VSCode\Cognizance\Resources\Task-4\iris.csv')

In [28]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4238 non-null   int64  
 1   age              4238 non-null   int64  
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64  
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64  
 7   prevalentHyp     4238 non-null   int64  
 8   diabetes         4238 non-null   int64  
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 529.9 KB


In [29]:
iris.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [30]:
iris.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [31]:
iris.dropna(inplace=True)
iris.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [32]:
y=iris.age

In [45]:
df=iris.drop(['age','currentSmoker','cigsPerDay','BPMeds','prevalentStroke','prevalentHyp','diabetes','TenYearCHD'],axis=1)

In [49]:
df.head()
x=df

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)


In [53]:
print("x_test",x_test.shape)
print("x_train",x_train.shape)
print("y_test",y_test.shape)
print("y_train",y_train.shape)

x_test (1097, 8)
x_train (2559, 8)
y_test (1097,)
y_train (2559,)


In [58]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [60]:
y_pred=classifier.predict(x_test)
print(y_pred)

[40 36 41 ... 46 40 44]


In [63]:
# Confusion Matrix
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import  classification_report,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy Score",accuracy_score(y_test,y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
Accuracy Score 0.037374658158614404


In [64]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          32       0.00      0.00      0.00         0
          33       0.00      0.00      0.00         2
          34       0.00      0.00      0.00         7
          35       0.02      0.12      0.04         8
          36       0.07      0.15      0.10        26
          37       0.08      0.21      0.12        24
          38       0.03      0.13      0.05        23
          39       0.04      0.07      0.05        45
          40       0.02      0.04      0.03        45
          41       0.01      0.03      0.02        36
          42       0.08      0.07      0.08        56
          43       0.02      0.03      0.02        36
          44       0.04      0.05      0.04        41
          45       0.05      0.04      0.05        47
          46       0.07      0.06      0.06        54
          47       0.07      0.06      0.06        32
          48       0.00      0.00      0.00        42
          49       0.03    

c:\Users\TEJASH REDDY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\TEJASH REDDY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\TEJASH REDDY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo